apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-provisioning
  namespace: prometheus-system
  labels:
    app.kubernetes.io/name: grafana
data:
  dashboards.yaml: |-
    apiVersion: 1
    
    # Ordner f√ºr Dashboards
    providers:
      - name: 'Immich Dashboards'
        orgId: 1
        folder: 'Immich'
        type: file
        disableDeletion: false
        updateIntervalSeconds: 10
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards