apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-config
  namespace: immich
  labels:
    app.kubernetes.io/instance: immich
    app.kubernetes.io/name: server
data:
  immich.json: |
    {
      "ffmpeg": {
        "accel": "nvenc",
        "accelDecode": true,
        "preferredHwDevice": "auto",
        "crf": 23,
        "threads": 0,
        "preset": "ultrafast"
      },
      "job": {
        "should_run": true,
        "concurrency": 1
      }
    }
