apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus-system
spec:
  selector:
    alertmanager: prometheus-kube-prometheus-alertmanager
    app.kubernetes.io/name: alertmanager
  ports:
    - name: http
      port: 80
      targetPort: 9093
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alertmanager
  namespace: prometheus-system
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: alertmanager
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: alertmanager
      port:
        number: 80
  tls:
    - hosts:
        - alertmanager
