apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus-system
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/hostname: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-kube-prometheus-prometheus
  ports:
    - name: http
      port: 80
      targetPort: 9090
    - name: https
      port: 443
      targetPort: 9090
  type: LoadBalancer
  loadBalancerClass: tailscale